name: PR comment and notify

on:
  pull_request:
    branches:
      - master

jobs:
  comment:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Post a comment on the PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'PR opened at ${{ github.event.pull_request.created_at  }} .Thanks for opening this PR! Automated review pipeline triggered.'
            })

      - name: Send email notification via Outlook SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port:  587
          secure: false #587 and false makes the connection upgrade to encrypted mid handshake unlike P465 which encrypts from start
          username: ${{ secrets.SMTP_EMAIL }}
          password: ${{ secrets.SMTP_PASSWORD  }}
          subject:  "New PR: ${{  github.event.pull_request.title }}"
          from: ${{ secrets.SMTP_EMAIL }}
          to: ${{ vars.OWNER_EMAIL }}
          body: |
            A new Pull request has been opened!

            Title   : ${{ github.event.pull_request.title }}
            Author  : ${{ github.event.pull_request.user.login }}
            Branch  : ${{ github.head_ref }} -> ${{ github.base_ref }}
            URL     : ${{ github.event.pull_request.html_url  }}

            Opened at : ${{ github.event.pull_request.created_at  }}
